### ISSUE TITLE
Page 94, template location for fill-murray addon incorrect

### ISSUE THREAD

**Issue by JonForest** [abuiles/ember-101#53]
On page 94 the following sentence is shown:
```Next we need to specify the body of our component in app/templates/components/fill-murray.hbs```

I'm fairly sure, that it should be:
```Next we need to specify the body of our component in addon/templates/components/fill-murray.hbs```

**Comment by ashleyconnor** [comment]
There seems to be quite a bit wrong with this section:

In order to get this to work I followed the book, combined with what you have also stated and then...

Edited `ember-cli-fill-murray/app/components/fill-murray.js` to contain:

```
import Ember from 'ember';
import FillMurray from 'ember-cli-fill-murray/components/fill-murray';

export default FillMurray;
```

Because the default export that existed didn't work. Which I found here [1].

Or if you want to skip this section just `npm install ember-cli-fill-murray-ashleyconnor`

[1] - [https://gist.github.com/kristianmandrup/ae3174217f68a6a51ed5#components](https://gist.github.com/kristianmandrup/ae3174217f68a6a51ed5#components)

**Comment by abuiles** [comment]
Thanks for reporting, I plan to do some updates soon.. trying to finish leanpub.com/json-api-by-example first :)

**Comment by abuiles** [comment]
This has been updated, thanks!
